substitutions:
  name: everything-presence-lite-6759ec
  friendly_name: Everything Presence Lite Bathroom
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: neDVd0pyVd08rFmp3EuZh+Ge/k3v2FFc4N/7Ud3HrRU=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
